### PR TITLE
Fix documentation on auth flow configuration

### PR DESCRIPTION
**Pull request by mistaecko**
Minor mixup in regards to what auth flow configuration is supported/required.
I was looking for a tool that supports SRP, and this minor mistake got my hopes up ;)

### CODE REVIEW

**Comment by sungly** [comment]
hey @mistaecko sorry about that! We did have a plan to add SRP login but never really got around to it. But if you're interested, we can definitely add it to this CLI.

**Comment by mistaecko** [comment]
@sungly, if cognito-cli had SRP support then our team would use it in our development workflow in order to obtain access tokens for interacting with the API via Postman or similar tools. I have not found any out-of-the-box solutions that provide SRP authentication. A common workaround is to enable `USER_PASSWORD_AUTH`, but this is not desirable in some environments.

**Comment by sungly** [comment]
> @sungly, if cognito-cli had SRP support then our team would use it in our development workflow in order to obtain access tokens for interacting with the API via Postman or similar tools. I have not found any out-of-the-box solutions that provide SRP authentication. A common workaround is to enable `USER_PASSWORD_AUTH`, but this is not desirable in some environments.

@mistaecko I put a pr for adding SRP authentication https://github.com/sungly/cognito-cli/pull/25, please feel free to provide feedback. Once I get a review from @rocellaj, we can publish this.

**Comment by sungly** [comment]
@mistaecko we published an update to do SRP login. We hope that this can help your team with some local development :D

**Pull request closed without merging**
